ДЗ 2. NumPy

Dataset - https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data

Завдання:

Знайти в датасеті таргет та видалити цю колонку з датасету (видаляти за індексом)
Перетворити колонки, що залишились в 2D масив (або впевнитись, що це уже 2D масив)
Порахувати mean, median, standard deviation для 1-ї колонки
Вставити 20 значень np.nan на випадкові позиції в масиві (при використанні звичайного рандому можуть накластись позиції, тому знайти рішення, яке гарантує 20 унікальних позицій)
Знайти позиції вставлених значень np.nan в 1-й колонці
Відфільтрувати массив за умовою: значення в 3-й колонці > 1.5 та значения в 1-й колонці < 5.0
Замінити всі значення np.nan на 0
Порахувати всі унікальні значення в массиві та вивести їх разом із кількісю
Розбити масив по горизонталі на 2 рівні частини (не використовувати абсолютні числа, мають бути два массиви по 4 колонки)
Відсортувати обидва массиви по 1-й колонці: 1-й за збільшенням, 2-й за зменшенням
Зібрати обидва массиви в одне ціле
Знайти найбільш часто повторюване значення в массиві
Написати функцію, яка б множила всі значення в колонці, які менше середнього значения в цій колонці, на 2, і ділила інші значення на 4.
Застосувати отриману функцію до 3-ї колонки

In [300]:
import numpy as np
import random

<center>1. Знайти в датасеті таргет та видалити цю колонку з датасету (видаляти за індексом)</center>

In [301]:
ds = np.genfromtxt('iris.data', delimiter=',')

In [302]:
ds = np.delete(ds, 4, 1)

<center>2. Перетворити колонки, що залишились в 2D масив (або впевнитись, що це уже 2D масив)</center>

In [303]:
ds = np.array(ds, ndmin = 2)
print('Num Dimension:', ds.ndim)

Num Dimension: 2


<center>3. Порахувати mean, median, standard deviation для 1-ї колонки</center>

In [304]:
print('mean of the first column is ', np.mean(ds[:, 0]))
print('median of the first column is ', np.median(ds[:, 0]))
print('standard deviation of the first column is ', np.std(ds[:, 0]))

mean of the first column is  5.843333333333334
median of the first column is  5.8
standard deviation of the first column is  0.8253012917851409


<center>4. Вставити 20 значень np.nan на випадкові позиції в масиві (при використанні звичайного рандому можуть накластись позиції, тому знайти рішення, яке гарантує 20 унікальних позицій)</center>

In [305]:
ds = ds.flatten()
i=len(np.where(np.isnan(ds) == True))
while i<20:
    n = random.randint(0, ds.shape[0]-1)
    if np.isnan(ds[n]):
        pass
    else:
        ds[n] = np.nan
        i += 1
ds = np.reshape(ds, (150, 4))
ds

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, nan, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [nan, 3.4, nan, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [nan, 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, nan],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

<center>5. Знайти позиції вставлених значень np.nan в 1-й колонці</center>

In [306]:
np.where(np.isnan(ds[:, 0]) == True)
ds

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, nan, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [nan, 3.4, nan, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [nan, 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, nan],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

<center>6. Відфільтрувати массив за умовою: значення в 3-й колонці > 1.5 та значения в 1-й колонці < 5.0</center>

In [307]:
ds = ds[(ds[:, 2]> 1.5) & (ds[:, 0]< 5.0)]

<center>7. Замінити всі значення np.nan на 0</center>

In [308]:
ds[np.isnan(ds)] = 0

<center>8. Порахувати всі унікальні значення в массиві та вивести їх разом із кількісю</center>

In [309]:
unique, counts = np.unique(ds, return_counts = True)
for i in range (0, len(unique)):
    print(f'кількість значень {unique[i]} = {counts[i]}')

кількість значень 0.0 = 1
кількість значень 0.2 = 3
кількість значень 1.6 = 3
кількість значень 1.7 = 1
кількість значень 1.9 = 1
кількість значень 2.5 = 1
кількість значень 3.1 = 1
кількість значень 3.2 = 1
кількість значень 3.4 = 2
кількість значень 4.5 = 1
кількість значень 4.7 = 1
кількість значень 4.8 = 3
кількість значень 4.9 = 1


<center>9. Розбити масив по горизонталі на 2 рівні частини (не використовувати абсолютні числа, мають бути два массиви по 4 колонки)</center>

In [310]:
if ds.shape[0] % 2 == 0:
    ds_new1, ds_new2 = np.split(ds, 2, axis = 0)
else:
    ds_new1, ds_new2 = np.split(ds[1:], 2, axis = 0)
    ds_new1 = np.vstack([ds[:1], ds_new1])

<center>10. Відсортувати обидва массиви по 1-й колонці: 1-й за збільшенням, 2-й за зменшенням</center>

In [311]:
ds_new1 = ds_new1[ds_new1[:, 0].argsort()]
ds_new2 = ds_new2[ds_new2[:, 0].argsort()[:: -1]]

<center>11. Зібрати обидва массиви в одне ціле</center>

In [312]:
ds = np.vstack([ds_new1, ds_new2])

<center>12. Знайти найбільш часто повторюване значення в массиві</center>

In [313]:
unique[np.argmax(counts)]

0.2

<center>13. Написати функцію, яка б множила всі значення в колонці, які менше середнього значения в цій колонці, на 2, і ділила інші значення на 4.</center>

In [314]:
def foo(arr, numb_col):
    mean = np.mean(arr[:, numb_col-1])
    arr[:, numb_col-1][(arr[:, numb_col-1] < mean)] *= 8
    arr[:, numb_col-1] /= 4
    


<center>14. Застосувати отриману функцію до 3-ї колонки</center>

In [315]:
foo(ds, 3)
ds

array([[4.7  , 3.2  , 3.2  , 0.   ],
       [4.8  , 3.4  , 3.2  , 0.2  ],
       [4.8  , 3.4  , 3.8  , 0.2  ],
       [4.9  , 2.5  , 1.125, 1.7  ],
       [4.8  , 3.1  , 3.2  , 0.2  ]])